[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "22.14.0"

[[headers]]
  for = "/*"
    [headers.values]
    Content-Type = "text/html"